=== FGover/rpc/rpc-framework/rpc-core/target/classes/rpc-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!ELEMENT configuration (
                port?,
                applicationName?,
                registry?,
                serializeType?,
                serializer?,
                compressType?,
                compressor?,
                loadBalancerType?,
                loadBalancer?,
                limiter?,
                idGenerator?
                )>

        <!-- 端口 -->
        <!ELEMENT port (#PCDATA)>

        <!-- 应用名称 -->
        <!ELEMENT applicationName (#PCDATA)>

        <!-- 注册中心 -->
        <!ELEMENT registry EMPTY>
        <!ATTLIST registry
                url CDATA #REQUIRED>

        <!-- 序列化类型 -->
        <!ELEMENT serializeType EMPTY>
        <!ATTLIST serializeType
                type CDATA #REQUIRED
                >
        <!-- 序列化实现 -->
        <!ELEMENT serializer EMPTY>
        <!ATTLIST serializer
                class CDATA #REQUIRED
                type CDATA #REQUIRED
                code CDATA #REQUIRED
                >

        <!-- 压缩类型 -->
        <!ELEMENT compressType EMPTY>
        <!ATTLIST compressType
                type CDATA #REQUIRED
                >

        <!-- 压缩实现 -->
        <!ELEMENT compressor EMPTY>
        <!ATTLIST compressor
                class CDATA #REQUIRED
                type CDATA #REQUIRED
                code CDATA #REQUIRED
                >

        <!-- 负载均衡类型 -->
        <!ELEMENT loadBalancerType EMPTY>
        <!ATTLIST loadBalancerType
                type CDATA #REQUIRED
                >

        <!-- 负载均衡实现 -->
        <!ELEMENT loadBalancer EMPTY>
        <!ATTLIST loadBalancer
                class CDATA #REQUIRED
                >

        <!-- 限流器 -->
        <!ELEMENT limiter EMPTY>
        <!ATTLIST limiter
                type              CDATA  #IMPLIED
                capacity          CDATA  #IMPLIED
                refillPerSecond   CDATA  #IMPLIED
                qps               CDATA  #IMPLIED
                windowMs          CDATA  #IMPLIED
                leakPerSecond     CDATA  #IMPLIED
                maxRequests       CDATA  #IMPLIED
                >

        <!-- ID生成器 -->
        <!ELEMENT idGenerator EMPTY>
        <!ATTLIST idGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                machineId CDATA #REQUIRED
                >

=== FGover/rpc/rpc-framework/rpc-core/target/classes/rpc-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "rpc-config.dtd">
<configuration>
    <port>8088</port>
    
    <applicationName>rpc-default-appName</applicationName>
    
    <registry url="zookeeper://127.0.0.1:2181"/>
<!--    <registry url="nacos://127.0.0.1:8848"/>-->

    <serializeType type="hessian"/>
    <!-- 额外添加的时候可用到（不修改SPI），和SPI本质一样-->
<!--    <serializer code="1" type="jdk" class="com.fg.serializer.service.impl.JdkSerializer"/>-->

    <compressType type="gzip"/>
    <!-- 额外添加的时候可用到（不修改SPI），和SPI本质一样 -->
<!--    <compressor code="1" type="gzip" class="com.fg.compressor.service.impl.GzipCompressor"/>-->

    <loadBalancer class="com.fg.loadbalancer.service.impl.ConsistentHashLoadBalancer"/>

    <!-- 滑动窗口：1秒最多100次 -->
    <limiter type="sliding" maxRequests="10" windowMs="1000"/>

    <!-- 令牌桶：容量10，每秒补5个 -->
    <!-- <limiter type="token" capacity="10" refillPerSecond="5"/> -->

    <!-- 固定窗口：1秒最多200次 -->
    <!-- <limiter type="fixed" qps="200" windowMs="1000"/> -->

    <!-- 漏桶：容量100，出水速率50/s -->
    <!-- <limiter type="leaky" capacity="100" leakPerSecond="50"/> -->

    <idGenerator class="com.fg.IdGenerator" dataCenterId="1" machineId="2"/>
</configuration>

=== FGover/rpc/demo/rpc-provider-demo/src/main/resources/rpc-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "rpc-config.dtd">
<configuration>
    <port>8090</port>
    
    <applicationName>rpc-default-appName</applicationName>
    
    <registry url="zookeeper://127.0.0.1:2181"/>

    <serializeType type="jdk"/>
    <serializer class="com.fg.serialize.service.Impl.HessianSerializer"/>

    <compressType type="gzip"/>
    <compressor class="com.fg.compress.service.Impl.GzipCompressor"/>
    
    <loadBalancerType type="RoundRobin"/>
    <loadBalancer class="com.fg.loadbalancer.service.Impl.RoundRobinLoadBalancer"/>

    <idGenerator class="com.fg.IdGenerator" dataCenterId="1" machineId="2"/>
</configuration>

=== FGover/rpc/rpc-framework/rpc-core/src/main/resources/rpc-config.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "rpc-config.dtd">
<configuration>
    <port>8088</port>
    
    <applicationName>rpc-default-appName</applicationName>
    
    <registry url="zookeeper://127.0.0.1:2181"/>

    <serializeType type="hessian"/>
    <serializer code="3" type="hessian" class="com.fg.serialize.service.impl.HessianSerializer"/>

    <compressType type="gzip"/>
    <compressor code="1" type="gzip" class="com.fg.compress.service.impl.GzipCompressor"/>

    <loadBalancerType type="RoundRobin"/>
    <loadBalancer class="com.fg.loadbalancer.service.impl.RoundRobinLoadBalancer"/>

    <idGenerator class="com.fg.IdGenerator" dataCenterId="1" machineId="2"/>
</configuration>
